#!/bin/sh

./makedtx.pl -dir tex -doc doc/test.tex -src 'arabmaths\.tex=>arabmaths.tex' -src 'autofootnoterule\.tex=>autofootnoterule.tex' -src 'luabidi\.sty=>luabidi.sty' -src 'textwidthfootnoterule\.tex=>textwidthfootnoterule.tex' luabidi 

tempdir=`mktemp -d`
srcdir=`pwd`
cd $tempdir
mkdir TDS
cd TDS
mkdir -p tex/lualatex/luabidi
mkdir -p doc/lualatex/luabidi
cp $srcdir/tex/* tex/lualatex/luabidi
cp $srcdir/doc/* doc/lualatex/luabidi
zip -ry luabidi.tds.zip *
cd ..
mkdir luabidi
cp $srcdir/luabidi.dtx luabidi
cp $srcdir/luabidi.ins luabidi
cp $srcdir/README luabidi
cp TDS/luabidi.tds.zip luabidi
zip -ry luabidi.zip luabidi
cd $srcdir

mv -f $tempdir/luabidi.zip .

echo "luabidi.zip is ready for upload to CTAN."

echo
echo "Checking structure ..."
cd $tempdir
mkdir check
cd check
unzip $srcdir/luabidi.zip
mkdir work
cd work
TEXINPUTS=../luabidi:
export TEXINPUTS
echo
lualatex luabidi.ins &>/dev/null
echo "Files produced by DTX:"
ls
cd ..
echo
echo "Content of TDS zip:"
zipinfo luabidi/luabidi.tds.zip
cd $srcdir

rm -rf $tempdir
