#!/bin/bash
# -*- coding: iso-8859-15 -*-

VERSION="2.6"
RELDATE="2025/06/30"

RUNTESTS=true

if [ $# -eq 1 ]; then
    # --notests
    if [ $1 == "--notests" -o $1 == "-t" ]; then
        RUNTESTS=false
    fi
fi

if [ $RUNTESTS = true ]; then
    l3build prerelease $EXTRAOPTS --date $RELDATE $VERSION
else
    echo "skipping tests!"
    l3build prerelease -c configfiles/config-nil --date $RELDATE $VERSION
fi
